/**
 * Export Handler Module
 * Handles CSV, Excel, and PDF exports
 */

class ExportHandler {
    /**
     * Export data to CSV
     * @param {Array} evaluations - Array of state evaluations
     * @param {Object} userInputs - User input data
     * @returns {string} CSV content
     */
    static exportToCSV(evaluations, userInputs = {}) {
        const headers = [
            'State',
            'State Code',
            'Risk Level',
            'Has Nexus',
            'Revenue',
            'Revenue Threshold',
            'Transactions',
            'Transaction Threshold',
            'Percent to Threshold',
            'Triggered By',
            'Notes'
        ];

        let csv = headers.join(',') + '\n';

        evaluations
            .filter(e => e.thresholdDetails)
            .forEach(evaluation => {
                const row = [
                    `"${evaluation.stateName}"`,
                    evaluation.stateAbbr,
                    evaluation.riskLevel,
                    evaluation.hasNexus,
                    evaluation.thresholdDetails.applicableRevenue || 0,
                    evaluation.thresholdDetails.revenueThreshold || 'N/A',
                    evaluation.thresholdDetails.applicableTransactions || 0,
                    evaluation.thresholdDetails.transactionThreshold || 'N/A',
                    evaluation.percentComplete.toFixed(2),
                    evaluation.triggeredBy || 'N/A',
                    `"${(evaluation.complianceInfo?.notes || '').replace(/"/g, '""')}"`
                ];
                csv += row.join(',') + '\n';
            });

        // Add metadata footer
        csv += '\n\nGenerated By,Sales Tax Nexus Tracker\n';
        csv += `Generated On,"${new Date().toLocaleString()}"\n`;
        csv += `Company Name,"${userInputs.companyName || 'N/A'}"\n`;
        csv += 'Disclaimer,"This report is for informational purposes only and does not constitute legal or tax advice."\n';

        return csv;
    }

    /**
     * Download CSV file
     * @param {Array} evaluations - Array of state evaluations
     * @param {Object} userInputs - User input data
     */
    static downloadCSV(evaluations, userInputs = {}) {
        const csv = this.exportToCSV(evaluations, userInputs);
        const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
        const link = document.createElement('a');
        const url = URL.createObjectURL(blob);

        link.setAttribute('href', url);
        link.setAttribute('download', `nexus-report-${new Date().toISOString().split('T')[0]}.csv`);
        link.style.visibility = 'hidden';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    }

    /**
     * Export to Excel using SheetJS
     * @param {Array} evaluations - Array of state evaluations
     * @param {Object} userInputs - User input data
     */
    static async downloadExcel(evaluations, userInputs = {}) {
        // Check if SheetJS is loaded
        if (typeof XLSX === 'undefined') {
            await this._loadSheetJS();
        }

        const wb = XLSX.utils.book_new();

        // Summary sheet
        const summaryData = this._prepareSummaryData(evaluations, userInputs);
        const summaryWS = XLSX.utils.aoa_to_sheet(summaryData);
        XLSX.utils.book_append_sheet(wb, summaryWS, 'Summary');

        // Detailed data sheet
        const detailData = this._prepareDetailData(evaluations);
        const detailWS = XLSX.utils.aoa_to_sheet(detailData);
        XLSX.utils.book_append_sheet(wb, detailWS, 'State Details');

        // States with nexus sheet
        const nexusStates = evaluations.filter(e => e.hasNexus);
        if (nexusStates.length > 0) {
            const nexusData = this._prepareNexusData(nexusStates);
            const nexusWS = XLSX.utils.aoa_to_sheet(nexusData);
            XLSX.utils.book_append_sheet(wb, nexusWS, 'Action Required');
        }

        // Write file
        XLSX.writeFile(wb, `nexus-report-${new Date().toISOString().split('T')[0]}.xlsx`);
    }

    /**
     * Load SheetJS library dynamically
     * @private
     */
    static _loadSheetJS() {
        return new Promise((resolve, reject) => {
            if (typeof XLSX !== 'undefined') {
                resolve();
                return;
            }

            const script = document.createElement('script');
            script.src = 'https://cdn.sheetjs.com/xlsx-0.20.1/package/dist/xlsx.full.min.js';
            script.onload = resolve;
            script.onerror = reject;
            document.head.appendChild(script);
        });
    }

    /**
     * Prepare summary data for Excel
     * @private
     */
    static _prepareSummaryData(evaluations, userInputs) {
        const summary = {
            nexusEstablished: evaluations.filter(e => e.riskLevel === 'NEXUS_ESTABLISHED').length,
            nexusImminent: evaluations.filter(e => e.riskLevel === 'NEXUS_IMMINENT').length,
            monitoring: evaluations.filter(e => e.riskLevel === 'MONITORING').length,
            noNexus: evaluations.filter(e => e.riskLevel === 'NO_NEXUS').length
        };

        return [
            ['Sales Tax Nexus Analysis Report'],
            [''],
            ['Company:', userInputs.companyName || 'N/A'],
            ['Generated:', new Date().toLocaleString()],
            ['Measurement Period:', userInputs.measurementPeriod || 'Not specified'],
            [''],
            ['SUMMARY'],
            ['States with Nexus Established:', summary.nexusEstablished],
            ['States with Imminent Nexus:', summary.nexusImminent],
            ['States Being Monitored:', summary.monitoring],
            ['States with No Concerns:', summary.noNexus],
            [''],
            ['DISCLAIMER'],
            ['This report is for informational purposes only and does not constitute legal or tax advice.'],
            ['Consult with a qualified tax professional regarding your specific situation.']
        ];
    }

    /**
     * Prepare detailed data for Excel
     * @private
     */
    static _prepareDetailData(evaluations) {
        const headers = [
            'State',
            'Code',
            'Risk Level',
            'Has Nexus',
            'Revenue',
            'Revenue Threshold',
            'Transactions',
            'Transaction Threshold',
            '% to Threshold',
            'Triggered By'
        ];

        const data = [headers];

        evaluations
            .filter(e => e.thresholdDetails)
            .forEach(e => {
                data.push([
                    e.stateName,
                    e.stateAbbr,
                    e.riskLevel,
                    e.hasNexus ? 'Yes' : 'No',
                    e.thresholdDetails.applicableRevenue || 0,
                    e.thresholdDetails.revenueThreshold || 'N/A',
                    e.thresholdDetails.applicableTransactions || 0,
                    e.thresholdDetails.transactionThreshold || 'N/A',
                    e.percentComplete.toFixed(2) + '%',
                    e.triggeredBy || 'N/A'
                ]);
            });

        return data;
    }

    /**
     * Prepare nexus states data for Excel
     * @private
     */
    static _prepareNexusData(nexusStates) {
        const headers = [
            'State',
            'Code',
            'Registration URL',
            'Filing Frequency',
            'Registration Timing',
            'Notes'
        ];

        const data = [
            ['STATES REQUIRING IMMEDIATE ACTION'],
            [''],
            headers
        ];

        nexusStates.forEach(e => {
            data.push([
                e.stateName,
                e.stateAbbr,
                e.complianceInfo.registrationUrl || 'N/A',
                e.complianceInfo.filingFrequency || 'N/A',
                e.complianceInfo.registrationTiming || 'N/A',
                e.complianceInfo.notes || ''
            ]);
        });

        return data;
    }

    /**
     * Export to PDF using jsPDF
     * @param {Array} evaluations - Array of state evaluations
     * @param {Object} userInputs - User input data
     */
    static async downloadPDF(evaluations, userInputs = {}) {
        // Check if jsPDF is loaded
        if (typeof jspdf === 'undefined') {
            await this._loadJsPDF();
        }

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();

        // Title
        doc.setFontSize(20);
        doc.text('Sales Tax Nexus Analysis Report', 20, 20);

        // Company info
        doc.setFontSize(12);
        doc.text(`Company: ${userInputs.companyName || 'N/A'}`, 20, 35);
        doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 42);

        // Summary
        doc.setFontSize(16);
        doc.text('Executive Summary', 20, 55);

        doc.setFontSize(11);
        const nexusCount = evaluations.filter(e => e.hasNexus).length;
        const imminentCount = evaluations.filter(e => e.riskLevel === 'NEXUS_IMMINENT').length;
        const monitoringCount = evaluations.filter(e => e.riskLevel === 'MONITORING').length;

        doc.text(`States with Nexus: ${nexusCount}`, 30, 65);
        doc.text(`States with Imminent Nexus: ${imminentCount}`, 30, 72);
        doc.text(`States Being Monitored: ${monitoringCount}`, 30, 79);

        let yPos = 95;

        // States requiring action
        if (nexusCount > 0) {
            doc.setFontSize(14);
            doc.text('States Requiring Immediate Action', 20, yPos);
            yPos += 10;

            doc.setFontSize(10);
            const nexusStates = evaluations.filter(e => e.hasNexus);
            nexusStates.forEach(state => {
                if (yPos > 270) {
                    doc.addPage();
                    yPos = 20;
                }
                doc.text(`• ${state.stateName} (${state.stateAbbr})`, 25, yPos);
                yPos += 7;
            });
        }

        // Disclaimer
        doc.addPage();
        doc.setFontSize(12);
        doc.text('Disclaimer', 20, 20);
        doc.setFontSize(10);
        const disclaimer = 'This report is for informational purposes only and does not constitute legal or tax advice. ' +
            'The information provided is based on current state laws and regulations as of the report date. ' +
            'State tax laws change frequently. Consult with a qualified tax professional regarding your specific situation.';
        const splitDisclaimer = doc.splitTextToSize(disclaimer, 170);
        doc.text(splitDisclaimer, 20, 30);

        // Save PDF
        doc.save(`nexus-report-${new Date().toISOString().split('T')[0]}.pdf`);
    }

    /**
     * Load jsPDF library dynamically
     * @private
     */
    static _loadJsPDF() {
        return new Promise((resolve, reject) => {
            if (typeof jspdf !== 'undefined') {
                resolve();
                return;
            }

            const script = document.createElement('script');
            script.src = 'https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
            script.onload = resolve;
            script.onerror = reject;
            document.head.appendChild(script);
        });
    }
}

// Export for use in other modules  
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ExportHandler;
}
